### ISSUE TITLE
VL53L1_ERROR_CALIBRATION_WARNING: Invalid calibration data

### ISSUE THREAD

**Issue by lfoscari** [melopero/Melopero_VL53L1X#5]
```bash
Python 3.7.3 [GCC 8.3.0] on linux
>>> import melopero_vl53l1x as mp
>>> sensor = mp.VL53L1X()
ioctl(I2C_RDWR) in i2c_write: Remote I/O error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/melopero_vl53l1x/VL53L1X.py", line 46, in __init__
    self._exception_check(status)
  File "/usr/local/lib/python3.7/dist-packages/melopero_vl53l1x/VL53L1X.py", line 111, in _exception_check
    raise Exception("VL53L1_ERROR_CALIBRATION_WARNING: Invalid calibration data")
Exception: VL53L1_ERROR_CALIBRATION_WARNING: Invalid calibration data
```

I'm running this on a Raspberry Pi 3B with the following pin configuration:
```
SDA    -> GPIO3
SCL    -> GPIO5
Ground -> GPIO9
VIN    -> GPIO1
```
Any ideas? Thanks in advance.

**Comment by leoli51** [comment]
Hello, 
Your pin configuration could be the problem. The device uses i2c to communicate with the raspberry therefore you should use a valid i2c configuration. Have you tried using the following pin configuration:
SDA  -> GPIO 2(SDA)
SLC  -> GPIO 3(SCL)
GND -> GND
VIN   -> 3.3V
I think you are using the physical numbering instead of the GPIO numbering, in fact the pin numbers you used 1,3,5,9 correspond to gpio 3.3V, GPIO 2, GPIO 3, GND. 
Otherwise you could check if the example is using the correct i2c address. By default the module uses 0x29. Type` i2cdetect -y 1` in the terminal and see if the device address is 0x29. If not you can use another address with :`sensor = mp.VL53L1X(myaddress)`
Let me know if this solves the issue.
Regards, 
Melopero Team.

**Comment by lfoscari** [comment]
Hello,
I tried the configuration you proposed but it still doesn't work, nothing changed. The output of `i2cdetect -y 1` is the following:
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 
```
Which I think means that no device is detected. Even though I enabled I2C and SPI via `raspi-config`. Is there something I forgot to enable?

note: I made a "map" of the pins I used, can you confirm me that are correct?

![](https://i.imgur.com/mTZ6mV8.png)

Thanks in advance

Thanks

**Comment by melopero** [comment]
Hello, 

The sensor should be detected with the command  `sudo i2cdetect -y 1`. 
Please contact **support@melopero.com** to receive assistance with one of our products. 

Best regards,  
Melopero Team

**Comment by lfoscari** [comment]
Thank you, I'll eventually write here the solution.
